### ISSUE TITLE
[Suggestion] Export / Save to png

### ISSUE THREAD

**Issue by TheMightyAtomNL** [XFactHD/AtlasViewer#1]
Suggestion to build in export / save to png functionality in AtlasViewer.

Ref: https://www.curseforge.com/private-messages/212368?comment=2

**Comment by XFactHD** [comment]
New version is available on CurseForge

**Comment by TheMightyAtomNL** [comment]
Hey, good work, just tried it and it works great. Thanks! :D

**Comment by XFactHD** [comment]
Thank you for the feedback :)
